#!/bin/bash
# Get current username
userName=$(whoami)
# Get current date and time
currentDate=$(date | awk '{print $1, $2, $3, $4}')
# Get system hostname
hostName=$(hostname)
# Get OS name and version
osName=$(hostnamectl | grep "Operating System" | awk -F': ' '{print $2}')
# Get system uptime
upTime=$(uptime -p)
# Get CPU model
cpuModel=$(lscpu | grep "Model name" | cut -d: -f2)
# Get total RAM
totalRam=$(cat /proc/meminfo | awk '/MemTotal/ {print $2 , $3}')
# List disks with size and model
diskInfo=$(lsblk -d -o NAME,SIZE,MODEL | sort -r | head -n 3)
# Get GPU model
gpuModel=$(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')
# Get fully qualified domain name
FDQN=$(hostname -f)
# Get main IP address
hostAddress=$(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
# Get default gateway IP
gatewayIP=$(ip r | grep default | awk '{print $3}')
# Get DNS server address
dnsServer=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)
# List logged-in users
loggedInUsers=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
# Show free space on partitions
diskSpace=$(df -h | awk '/^\/dev/ {print $6 " " $4}')
# Count running processes
processCount=$(ps -e | wc -l)
# Check system load averages
loadAvg=$(uptime | awk -F'average: ' '{print $2}')
# List open network ports
listeningPorts=$(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')
# Check firewall status
firewallStatus=$(sudo ufw status | grep Status | awk '{print $2}')

# Display system report
cat << EOF

System Report generated by $userName, $currentDate

System Information
------------------
Hostname: $hostName
OS: $osName
Uptime: $upTime

Hardware Information
--------------------
CPU: $cpuModel
RAM: $totalRam
Disk(s):
$diskInfo
Video: $gpuModel

Network Information
-------------------
FQDN: $fqdn
Host Address: $hostAddress
Gateway IP: $gatewayIp
DNS Server: $dnsServer

System Status
-------------
Users Logged In: $loggedInUsers
Disk Space: $diskSpace
Process Count: $processCount
Load Averages: $loadAvg
Listening Network Ports: $listeningPorts
UFW Status: $firewallStatus

EOF
